# Frontend nodes (chat clients)
host "chat1.local" {
    proxy_pass http://127.0.0.1:9001;
}

host "chat2.local" {
    proxy_pass http://127.0.0.1:9002;
}

host "chat3.local" {
    proxy_pass http://127.0.0.1:9003;
}

# Backend servers with load balancing
host "api.local" {
    proxy_pass http://127.0.0.1:9101;
    proxy_pass http://127.0.0.1:9102;
    proxy_pass http://127.0.0.1:9103;

    dist_policy round-robin
}

# Tracker server
host "tracker.local" {
    proxy_pass http://127.0.0.1:8000;
}
